language: python
jobs:
  include:
    - name: "Ubuntu Xenial with Python 3.9"
      os: linux
      python: 3.9.7
    - name: "macOS 11.6 with Python 3.9"
      os: osx
      osx_image: xcode13.1
      language: shell
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install pipenv
  - pipenv install --dev --skip-lock
script:
  - pipenv run py.test tests/tests.py

